### ISSUE TITLE
The color picker example is very slow.

### ISSUE THREAD

**Issue by GirkovArpa** [magicmouse/beads-examples#1]
It takes quite some time for the app to register that I clicked a button (as observed by how long it takes for my color to be highlighted).

As my first impression of an application of your language, this was not favorable.

**Comment by magicmouse** [comment]
i just tested that page, it and it responds to clicks instantly in Chrome on OSX.
what browser are you using? What OS?
wondering if the sound effects being played are somehow misbehaving.

the response to the tap is only a few lines of code:

  if (std.getn(e, std.F_evkind) == std.EV_TAP) {
    if ((getn(b.extra, std.F_cell_seq) === U || std.gt2(getn(b.extra, std.F_cell_seq), NCELLS))) {
      std.sound_play(BEEP, {});
      std.path_setv(_M, 357, addr(g, F_selectedx), U);
    } else {
      std.sound_play(CLICK, {});
      std.path_setv(_M, 361, addr(g, F_selectedx), getn(b.extra, std.F_cell_seq));
      std.os_to_clipboard(calc_slot_str(std.get_ptr(slotlist, getn(g, F_selectedx))));

so theoretically this should be instantaneous.
do you have some kind of protection program that worries about the clipboard? on a click in  a new cell,
it plays a sound, then sets the selected cell, then copies to the clipboard the color name so you can paste it in.

**Comment by GirkovArpa** [comment]
I had my volume off.  Oops.

**Comment by magicmouse** [comment]
thanks for reporting the error.

I don’t have very many users yet, and i appreciate you taking the time to send me a report.
I published a whole book on the language in the SDK, but alas people don’t have much spare time to learn a language
that will take ten hours to learn. To motivate people, i am building a Eat24/Uber Eats product in the language,
and it is already better than McDonald’s online app, so i am confident that full scale professional product will give people more confidence in the tool.

Girkov sounds like a name from Bulgaria if i had to guess.

edward
