### ISSUE TITLE
Correct setup for web server for Firefox testing?

### ISSUE THREAD

**Issue by celtic-coder** [magicmouse/beads-examples#4]
Hi Edward (@magicmouse),

I do not use Chrome for testing, so I used your suggestion for changing the value of *security.fileuri.strict_origin_policy* in Firefox. However, I could not get the Beads demo HTML files to load. They were all coming up blank.

I tried the suggestion in this article ([How do you set up a local testing server? - Learn web development | MDN](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server)) and setup a local web server using Python:

![CMD-Python-web-server](https://user-images.githubusercontent.com/11787866/139592217-aeac720f-90b7-4d80-ab1b-e242f6a8edc0.png)

The Beads compiler shows the base folder (**C:\Beads**):

![Beads-compiler-http-localhost](https://user-images.githubusercontent.com/11787866/139592364-2837929d-43ca-4a11-b356-c5ded6a63ddc.png)

The only way that I could get the demo files to work was to use http://localhost:8887/C:/Beads/ as the HTTP folder serving the runtimes. The JavaScript files were served correctly as can be seen from the source code of the "Watch" demo HTML file:

![watch-html-source-code](https://user-images.githubusercontent.com/11787866/139592550-6ad2e0b8-f023-41b8-a14a-993bd61cb139.png)

Is this the correct method for serving the JavaScript files? Might there be an alternative method that also works?

By the way, from the web server output it looks like only the *C:/Beads/runtime_047/beads_str.js* was required for the Watch demo. Is this correct?

Kind Regards,
Liam

**Comment by magicmouse** [comment]
The string library (beads_str) and the beads_std file Are always going to be required for any project. So as to keep your project files nice and small we isolate out the two runtime modules which will be used in every Beads program you write and are basically shared libraries. for a production Situation we have minimized modules but also you can compress them with a zip if you want to minimize download time. It all depends on your web server set up many Web servers are configured to automatically download compressed versions. I’m not that expert on Apache.

If you have the sample programs running then you are doing well. Fire fox is pretty good, it’s debugger is not quite as good as chrome, But it’s fine and it sounds like you’re up and running which is good to hear

— Whoever is happy will make others happy too

**Comment by celtic-coder** [comment]
Thanks for the confirmation!
